### ISSUE TITLE
[REQ] add/remove Ban, Mute, Gag via SteamID

### ISSUE THREAD

**Issue by audiomaster99** [Source2ZE/CS2Fixes#114]
Possibility to add/remove infractions via steamid if player is not on the server

**Comment by Vauff** [comment]
Unban is now implemented in https://github.com/Source2ZE/CS2Fixes/commit/05c7ef4feb09e2e30a0c38829e762efd79ad5517.

Mute/gag are less important, since the players can actually join to have those infractions removed. Going forward it's unlikely we'll develop the infraction system further, as servers continue to move to full-fledged distributed solutions, so I'm just gonna close this now.
