### ISSUE TITLE
Server print Unexpected long frame detected in log per 30 seconds when cs2fixs enable

### ISSUE THREAD

**Issue by CeLicat** [Source2ZE/CS2Fixes#211]
Only changed admins.cfg to give myself permission flags.
![Snipaste_2024-04-12_17-24-10](https://github.com/Source2ZE/CS2Fixes/assets/19570348/43fde7e5-f9ac-4894-a15c-9cd39732accd)

**Comment by xLeviNx** [comment]
This has nothing to do with CS2Fixes

**Comment by axl303** [comment]
> when cs2fixs enable

From the Issue title

As @xLeviNx said this has nothing with the plugin.

The problem comes (mostly) from slow CPU / using shared resources (VPS/VM..etc)
Tested on slow OVH VPS (overloaded or whatsoever) with and without this plugin, the server was spamming long frame, even with no bots, empty server etc..

The minimum dedicated hardware I had access and tested was on i7-4790K (default, no clock) and a DDR3 RAM and everything was fine.

My suggestion is to try on some decent or a dedicated CPU with Minimum of 3GHz and above. 
I think 3Ghz - 3.5GHz range should be enough and good, also use some newer CPU if possible. >= 2017y should be really OK.

If you ask/or others ask, what hardware should I use to run smooth servers and to not care that much:
Some decent cpu, ddr4/5 ram and a ssd/nvme with good/stable network.

At the moment of this comment date, the only thing is to have a decent CPU for this problem (LONG FRAME).
I am not fully sure that VALVe will give some light to this problem. Many users are facing it.

Hope I gave some light in the tunnel for people seeking information and trying things for this issue.

**Comment by CeLicat** [comment]
> > when cs2fixs enable
> 
> From the Issue title
> 
> As @xLeviNx said this has nothing with the plugin.
> 
> The problem comes (mostly) from slow CPU / using shared resources (VPS/VM..etc) Tested on slow OVH VPS (overloaded or whatsoever) with and without this plugin, the server was spamming long frame, even with no bots, empty server etc..
> 
> The minimum dedicated hardware I had access and tested was on i7-4790K (default, no clock) and a DDR3 RAM and everything was fine.
> 
> My suggestion is to try on some decent or a dedicated CPU with Minimum of 3GHz and above. I think 3Ghz - 3.5GHz range should be enough and good, also use some newer CPU if possible. >= 2017y should be really OK.
> 
> If you ask/or others ask, what hardware should I use to run smooth servers and to not care that much: Some decent cpu, ddr4/5 ram and a ssd/nvme with good/stable network.
> 
> At the moment of this comment date, the only thing is to have a decent CPU for this problem (LONG FRAME). I am not fully sure that VALVe will give some light to this problem. Many users are facing it.
> 
> Hope I gave some light in the tunnel for people seeking information and trying things for this issue.

Thanks for your reply.

I use Xeon E3-1270 v5 for this server with plugin enabled still get this issue. The weird thing is that I didn't notice this situation before I used an I5-2400 CPU as a host.

Now i can see this issue is nothing with the plugin so i perfer it might be due to some game update from VALve.

Anyways, thx all relplies, Best wishes.
