### ISSUE TITLE
Windows crashes

### ISSUE THREAD

**Issue by TN141** [Source2ZE/CS2Fixes#286]
[CS2Fxies] Failed to find address for CBaseEntity_TakeDamageOld
Failed to load plugin addons\cs2fixes\bin\win64\cs2fixes: One or more address lookups, patches or detours failed, please refer to startup logs for more information.

Version: 1.8.10

**Comment by Gawnz1** [comment]
Can CBaseEntity_TakeDamageOld be hooked like the TakedamageAlive one, so we can be a bit more safe from updates and to avoid failures such as this.
Or is there any way to make it without signature, address somehow.

**Comment by Vauff** [comment]
Maybe verify your gamedata file is also updated? v1.8.10 starts fine on my Windows test server.

`[CS2Fixes] Detoured CBaseEntity_TakeDamageOld at 0x00007FFFC5B207C0`

> Can CBaseEntity_TakeDamageOld be hooked like the TakedamageAlive one, so we can be a bit more safe from updates and to avoid failures such as this. Or is there any way to make it without signature, address somehow.

Offsets aren't inherently more stable than signatures, it's a case by case thing. In this case, the signature is actually more stable, since it's only ever broken once since we added it, whereas entity offsets shifted several times in the same period. It's also a lot easier to automatically identify signature breakage with our current tooling.

**Comment by Vauff** [comment]
This is actually likely a conflict with another plugin. Notably, CS# may be compatible, but a CS# plugin may have detoured TakeDamageOld, causing incompatibility.

The proper solution to this would be Metamod getting a detour manager that all plugins can use, which is out of scope for us.

**Comment by TN141** [comment]
Hello! @Gawnz1 I have a completely new server that was created locally a few days ago. It does indeed have CS#. I also confirmed that the problem is not just with me. Neither I nor my friend are experiencing any issues on Linux.
