### ISSUE TITLE
Can support the rampbug fix?

### ISSUE THREAD

**Issue by 2vg** [Source2ZE/CS2Fixes#296]
Hello, thank you for the great plugin.
I read an interesting article about surf's rampbugfix in cs2. [rampbugfix.md](https://gist.github.com/zer0k-z/2eb0c230c8f2c62b5c46d36353cf8d8d)
The article mentions a plugin solution, but it was implemented as part of a big plugin.
I want only the "Fix", so are there any plans to implement something like this? Thanks!

**Comment by Vauff** [comment]
We currently don't plan to add it, due to the complexity/invasiveness factor compared to its benefit for ZE (the majority of ZE maps do not have surf elements, and hitting a rampbug isn't really end of the world due to being non-competitive). There is also apparently a performance penalty, which is concerning in an already constrained 64 player environment.
