### ISSUE TITLE
adminsystem and getreason

### ISSUE THREAD

**Issue by xyzelt** [Source2ZE/CS2Fixes#321]
I don't know if there are a mistake, but there are not GetReason in ParseInfraction, so even if admin put an reason, will not be promted.
I see GetReason in pm cmd to catch private message.
Maybe add in ParseInfraction something like:
...
		ClientPrint(pAdmin, HUD_PRINTTALK, CHAT_PREFIX "Invalid duration.");
		return;
	}
	std::string strReason;
	if (bAdding)strReason = GetReason(args, 2, false);
	if(strReason !="")strReason=std::string(" Reason:"+strReason);
....
and printout
...
				//PrintSingleAdminAction(pszCommandPlayerName, pTarget->GetPlayerName(), GetActionPhrase(infType, GrammarTense::Past, bAdding), (" for " + FormatTime(iDuration, false)).c_str());
				PrintSingleAdminAction(pszCommandPlayerName, pTarget->GetPlayerName(), GetActionPhrase(infType, GrammarTense::Past, bAdding), (" for " + FormatTime(iDuration, false) + strReason).c_str());
			else
			{
				std::string strAction = "permanently ";
				strAction +=strReason;

**Comment by Vauff** [comment]
This is a feature that would generally make sense. However, with the more mature state of CS2 modding, communities are already moving to more advanced punishment systems, and doing further feature development on a local-only system is a bit of wasted effort. We'll probably just maintain it as-is going forward, since at least [one](https://github.com/Frozen-H2O/CS2_Fixes/tree/gflbans) of the more advanced systems forks off of it.
